# Notebooks 05 (gravity+resim) + 06 (twin) — executed by _build_notebooks.py.

# ════════════════════════════════════════════════════════════════════════
# 05 — Gravity in a box & selective resimulation
# ════════════════════════════════════════════════════════════════════════
save("05_gravity_and_resimulation.ipynb", [
    md("# 05 · Gravity in a box & selective resimulation\n"
       "*A particle-mesh solver validated against linear theory, and the "
       "TreePM force split that makes sub-volume resimulation affordable.*\n\n"
       "The built-in PM solver (cloud-in-cell deposit → FFT Poisson → "
       "kick-drift-kick leapfrog) lets the package exercise gravity without an "
       "external N-body code. We *watch* structure grow, verify the growth "
       "rate against the exact linear factor D(a), then attack the mini-sim "
       "paradox: a resimulated tile cannot feel large-scale tides beyond its "
       "buffer — unless the force is split by scale."),
    code(SETUP),
    md("## Watching structure grow — and checking it grows *right*\n"
       "Four PM runs of the same initial conditions to increasing scale "
       "factors. Overlay: the fluctuation amplitude of each snapshot against "
       "the exact linear-theory growth factor D(a)."),
    code("from oneuniverse.simulation.linear.gaussian_field import generate_density_field\n"
         "from oneuniverse.simulation.pm.run import run_pm, zeldovich_pm_ic_from_field\n"
         "from oneuniverse.simulation.pm.deposit import deposit_cic\n"
         "from oneuniverse.simulation.linear.growth import growth_factor\n"
         "BOX,N=300.0,64\n"
         "ic=generate_density_field(COSMO,box_size=BOX,n_grid=N,z=0.0,seed=4)\n"
         "a_targets=[0.25,0.5,0.75,1.0]\n"
         "fields=[]\n"
         "for a_end in a_targets:\n"
         "    nst=max(6,int(20*a_end))\n"
         "    x,_=run_pm(*zeldovich_pm_ic_from_field(COSMO,ic,box=BOX,n_grid=N,z_start=9.0),\n"
         "               box=BOX,n_grid=N,cosmo=COSMO,a_start=0.1,a_end=a_end,n_steps=nst)\n"
         "    rho=deposit_cic(x,N,BOX); fields.append(rho/rho.mean()-1)\n"
         "sl=N//2\n"
         "fig,ax=plt.subplots(1,5,figsize=(16,3.5))\n"
         "for i,(a,f) in enumerate(zip(a_targets,fields)):\n"
         "    im=ax[i].imshow(f[:,:,sl].T,origin='lower',cmap='magma',vmin=-1,vmax=4)\n"
         "    ax[i].set_title(f'a = {a}  (z = {1/a-1:.1f})'); ax[i].axis('off')\n"
         "D=[growth_factor(1/a-1,COSMO) for a in a_targets]\n"
         "sig=[f.std() for f in fields]\n"
         "ax[4].plot(D/np.asarray(D[-1]), sig/np.asarray(sig[-1]),'o',ms=8,color=C1,label='PM σ(δ)')\n"
         "ax[4].plot([0,1],[0,1],'-',color='.5',label='linear D(a)')\n"
         "ax[4].set_xlabel('D(a)/D(1)'); ax[4].set_ylabel('σ_PM(a)/σ_PM(1)')\n"
         "ax[4].set_title('growth follows D(a)'); ax[4].legend(fontsize=8.5)\n"
         "plt.tight_layout(); plt.show()\n"
         "r=np.corrcoef(D,sig)[0,1]; print('amplitude vs D(a): corr = %.4f'%r)"),
    md("## Phases and amplitude: the field-validation estimators\n"
       "The package's canonical estimators — cross-correlation r(k) (phases) "
       "and transfer T(k) (amplitude) — against the z=0 linear field."),
    code("from oneuniverse.simulation.validation import validate_field\n"
         "v=validate_field(fields[-1],ic,box=BOX)\n"
         "fig,ax=plt.subplots(1,2,figsize=(12,3.8))\n"
         "ax[0].semilogx(v.k,v.r,'o-',color=C0,label='r(k) phases')\n"
         "ax[0].semilogx(v.k,v.transfer,'s-',color=C1,label='T(k) amplitude')\n"
         "ax[0].axhline(1,color='.6',ls='--'); ax[0].set_ylim(0,1.12)\n"
         "ax[0].set_xlabel('k [h/Mpc]'); ax[0].legend(); ax[0].set_title('PM vs linear theory')\n"
         "ax[1].semilogx(v.k,v.stochasticity,'d-',color=C4)\n"
         "ax[1].set_xlabel('k [h/Mpc]'); ax[1].set_ylabel('1 − r²')\n"
         "ax[1].set_title('stochasticity: the non-linear, irreducible part')\n"
         "plt.tight_layout(); plt.show()\n"
         "lo=v.k<0.06\n"
         "print('large scales:  r=%.3f  T=%.3f'%(np.nanmedian(v.r[lo]),np.nanmedian(v.transfer[lo])))"),
    md("## The TreePM force split — the idea, drawn\n"
       "Split gravity in Fourier space: the **long-range tide** comes from the "
       "full-box linear field (low-pass, scaled by D(a)); the **short-range** "
       "force from the tile's own PM (high-pass). The two filters are exactly "
       "complementary, so nothing is double-counted."),
    code("kk=np.logspace(-2,0.4,300); ks=0.12\n"
         "W=np.exp(-0.5*(kk/ks)**2)\n"
         "fig,ax=plt.subplots(figsize=(8.5,3.6))\n"
         "ax.semilogx(kk,W,lw=2.6,color=C0,label='long-range  W(k) — full-box LINEAR field, ∝D(a)')\n"
         "ax.semilogx(kk,1-W,lw=2.6,color=C1,label='short-range 1−W(k) — tile PM force')\n"
         "ax.fill_between(kk,0,W,color=C0,alpha=.12); ax.fill_between(kk,0,1-W,color=C1,alpha=.12)\n"
         "ax.axvline(ks,color='.4',ls=':',lw=1.5); ax.text(ks*1.1,0.5,'k_split',fontsize=10,color='.3')\n"
         "ax.set_xlabel('k [h/Mpc]'); ax.set_ylabel('force fraction')\n"
         "ax.set_title('TreePM split: complementary in k — no double counting')\n"
         "ax.legend(fontsize=9, loc='center right'); plt.show()"),
    md("## Does it pay? Buffer convergence\n"
       "Inner-region fidelity vs buffer size, naive uncoupled tile vs "
       "TreePM-coupled tile, against a full-box reference."),
    code("from oneuniverse.simulation.resim.bench import reference_inner, uncoupled_resim_fn\n"
         "from oneuniverse.simulation.resim.treepm import run_coupled_treepm\n"
         "KW=dict(box=300.0,n_grid=64,target_lo=112.0,target_side=76.0,seed=4,n_steps=18)\n"
         "ref=reference_inner(COSMO,**KW)\n"
         "unc=uncoupled_resim_fn(COSMO,**KW)\n"
         "tp=lambda b: run_coupled_treepm(COSMO,ic,box=KW['box'],n_grid=KW['n_grid'],\n"
         "    target_lo=KW['target_lo'],target_side=KW['target_side'],buffer=b,\n"
         "    z_start=9.0,z_end=0.0,n_steps=KW['n_steps'])['inner']\n"
         "co=lambda a: float(np.corrcoef(a.ravel(),ref.ravel())[0,1])\n"
         "buffers=[8.,16.,24.,32.,48.]\n"
         "cu=[co(unc(b)) for b in buffers]; ct=[co(tp(b)) for b in buffers]\n"
         "fig,ax=plt.subplots(1,2,figsize=(12.5,4.2))\n"
         "ax[0].plot(buffers,cu,'o-',color=C0,lw=2,label='uncoupled tile (baseline)')\n"
         "ax[0].plot(buffers,ct,'s-',color=C1,lw=2,label='TreePM-coupled tile')\n"
         "ax[0].set_xlabel('buffer [Mpc/h]'); ax[0].set_ylabel('corr. with full-box truth')\n"
         "ax[0].set_ylim(0,1); ax[0].legend(); ax[0].set_title('buffer convergence')\n"
         "gains=[t-u for t,u in zip(ct,cu)]\n"
         "ax[1].bar([str(int(b)) for b in buffers],gains,color=C2)\n"
         "ax[1].set_xlabel('buffer [Mpc/h]'); ax[1].set_ylabel('Δ corr (TreePM − uncoupled)')\n"
         "ax[1].set_title('the coupling gain at every buffer')\n"
         "plt.tight_layout(); plt.show()\n"
         "print('TreePM@%g (%.2f) vs uncoupled@%g (%.2f) — comparable accuracy at a much smaller buffer'\n"
         "      %(buffers[0],ct[0],buffers[-1],cu[-1]))"),
    md("**What this showed.** The PM solver grows structure on the exact "
       "linear-theory curve and recovers phases+amplitude at large scales; "
       "the resimulation problem is the missing large-scale tide; and the "
       "scale-split force closes most of that gap at every buffer size — the "
       "economics that make selective zoom resimulation viable."),
])

# ════════════════════════════════════════════════════════════════════════
# 06 — The constrained twin
# ════════════════════════════════════════════════════════════════════════
save("06_constrained_twin.ipynb", [
    md("# 06 · The constrained twin\n"
       "*From noisy biased tracers back to the cosmic web — and what survey "
       "depth buys you.*\n\n"
       "The end-game is a simulation **constrained by data**. The minimal "
       "engine is the Wiener filter — the optimal linear estimator\n"
       "$$\\hat\\delta(k)=\\underbrace{\\frac{bP(k)}{b^2P(k)+1/\\bar n}}_{G(k)}\\,\\delta_g(k)$$\n"
       "— plus **constrained realizations** (Hoffman–Ribak): the Wiener mean "
       "with statistically-correct small-scale power filled back in."),
    code(SETUP),
    md("## The filter itself\n"
       "The Wiener gain G(k) for several tracer densities: deeper surveys "
       "(higher n̄) trust the data to smaller scales."),
    code("from oneuniverse.simulation.linear.power_spectrum import linear_power\n"
         "kk=np.logspace(-2,0.3,250); P=linear_power(kk,COSMO,z=0.0); bias=1.5\n"
         "fig,ax=plt.subplots(figsize=(8.5,3.8))\n"
         "for nb,c in zip([3e-4,1e-3,5e-3,3e-2],[C3,C2,C0,C4]):\n"
         "    G=bias*P/(bias**2*P+1/nb)\n"
         "    ax.semilogx(kk,G,lw=2.4,color=c,label=f'n̄ = {nb:.0e} (h/Mpc)³')\n"
         "ax.axhline(1/bias,color='.55',ls='--',lw=1); ax.text(.011,1/bias+.02,'1/b (signal-dominated)',fontsize=8.5,color='.4')\n"
         "ax.set_xlabel('k [h/Mpc]'); ax.set_ylabel('Wiener gain G(k)')\n"
         "ax.set_title('the filter: keep high-S/N modes, kill shot noise'); ax.legend(fontsize=9)\n"
         "plt.show()"),
    md("## Truth → tracers → Wiener mean → constrained realization\n"
       "Linear-bias Poisson tracers (shot-noise-limited — the regime the "
       "linear filter is optimal for). The Wiener mean is smooth where data is "
       "uninformative; the constrained realization restores realistic "
       "small-scale texture while honouring the data."),
    code("from oneuniverse.simulation.linear.gaussian_field import generate_density_field\n"
         "from oneuniverse.twin.mock_observe import mock_tracer_field\n"
         "from oneuniverse.twin.wiener import wiener_reconstruct\n"
         "from oneuniverse.twin.constrained import constrained_realization\n"
         "from oneuniverse.twin.verify import cross_correlation\n"
         "BOX,N=400.0,96; bias=1.5; nbar=5e-3\n"
         "truth=generate_density_field(COSMO,box_size=BOX,n_grid=N,z=0.0,seed=5)\n"
         "obs=mock_tracer_field(truth,box_size=BOX,nbar=nbar,bias=bias,seed=6,model='clip')\n"
         "rec=wiener_reconstruct(obs['delta_g'],COSMO,box_size=BOX,nbar=nbar,bias=bias,z=0.0)\n"
         "cr=constrained_realization(obs['delta_g'],COSMO,box_size=BOX,nbar=nbar,bias=bias,z=0.0,seed=11)\n"
         "sl=N//2\n"
         "fig,ax=plt.subplots(1,4,figsize=(16,3.9))\n"
         "for a,f,t in ((ax[0],truth,'truth δ'),(ax[1],obs['delta_g'],'observed tracers δ_g'),\n"
         "              (ax[2],rec,'Wiener mean'),(ax[3],cr,'constrained realization')):\n"
         "    im=a.imshow(f[:,:,sl].T,origin='lower',cmap='magma',vmin=-1.2,vmax=3)\n"
         "    a.set_title(t); a.axis('off')\n"
         "plt.tight_layout(); plt.show()\n"
         "print('variance:  truth %.2f | Wiener %.2f (over-smooth, by design) | constrained %.2f (restored)'\n"
         "      %(truth.var(),rec.var(),cr.var()))"),
    md("## Fidelity, quantified — and the depth–fidelity law\n"
       "r(k) between reconstruction and truth for a range of survey depths; "
       "the reconstruction scale $k_{1/2}$ (where r = 0.5) tightens "
       "monotonically with n̄."),
    code("def khalf_for(nb,seed=10):\n"
         "    o=mock_tracer_field(truth,box_size=BOX,nbar=nb,bias=bias,seed=seed,model='clip')\n"
         "    rr=wiener_reconstruct(o['delta_g'],COSMO,box_size=BOX,nbar=nb,bias=bias,z=0.0)\n"
         "    kk2,r2=cross_correlation(rr,truth,box_size=BOX)\n"
         "    bel=np.where(r2<0.5)[0]\n"
         "    return (kk2[bel[0]] if len(bel) else kk2[-1]), kk2, r2\n"
         "nbars=[3e-4,1e-3,5e-3,1.5e-2,3e-2]\n"
         "res=[khalf_for(nb) for nb in nbars]\n"
         "fig,ax=plt.subplots(1,2,figsize=(12.5,4.2))\n"
         "cmap=plt.cm.viridis(np.linspace(.15,.9,len(nbars)))\n"
         "for (nb,(kh,kk2,r2)),c in zip(zip(nbars,res),cmap):\n"
         "    ax[0].plot(kk2,r2,lw=2,color=c,label=f'n̄={nb:.0e}')\n"
         "ax[0].axhline(.5,color='.6',ls='--'); ax[0].set_xlim(0,0.9); ax[0].set_ylim(0,1.03)\n"
         "ax[0].set_xlabel('k [h/Mpc]'); ax[0].set_ylabel('r(k) reconstruction × truth')\n"
         "ax[0].legend(fontsize=8); ax[0].set_title('fidelity vs survey depth')\n"
         "ax[1].semilogx(nbars,[kh for kh,_,_ in res],'o-',color=C1,lw=2,ms=8)\n"
         "ax[1].set_xlabel('tracer density n̄ [(h/Mpc)³]'); ax[1].set_ylabel('k(r=0.5) [h/Mpc]')\n"
         "ax[1].set_title('the depth → reconstructable-scale law')\n"
         "plt.tight_layout(); plt.show()\n"
         "print('k_half:', ', '.join('%.2f'%kh for kh,_,_ in res))"),
    md("**What this showed.** The exact filter the package applies, the full "
       "chain truth→observation→reconstruction→constrained realization on a "
       "controlled mock (where the answer is known), and the quantitative law "
       "tying survey depth to the smallest reconstructable scale — the "
       "trade-off any constrained-simulation programme lives on. The Gaussian/"
       "linear engine is the MVP; the architecture (engines, store boundary, "
       "orchestration) is the part built for the real thing."),
])
