# Notebooks 03 (measure) + 04 (sim store) — executed by _build_notebooks.py.

# ════════════════════════════════════════════════════════════════════════
# 03 — Measurements for every probe
# ════════════════════════════════════════════════════════════════════════
save("03_measurements_every_probe.ipynb", [
    md("# 03 · Measurements for every probe\n"
       "*One cosmology-free output — the `MeasurementSet` — for clustering, "
       "lensing, velocities, supernovae, Lyα and maps.*\n\n"
       "`oneuniverse.measure` runs a nine-step preparation pipeline and emits "
       "one container regardless of probe. Cosmology never enters — it is "
       "chosen later, at the estimator call, so the same prepared measurement "
       "is reusable under any fiducial. Real eBOSS for clustering; controlled "
       "synthetic data for the probes whose real catalogs are not on disk."),
    code(SETUP),
    md("## The nine-step pipeline"),
    code("steps=['select','clean','weight','window','n(z)','randoms','photo-z','region','spec']\n"
         "cols=[C0,C0,C3,C2,C2,C2,C4,C1,C1]\n"
         "fig,ax=plt.subplots(figsize=(13,1.9)); ax.axis('off'); ax.set_xlim(0,13); ax.set_ylim(0,2)\n"
         "for i,(s,c) in enumerate(zip(steps,cols)):\n"
         "    x=0.25+i*1.42\n"
         "    ax.add_patch(FancyBboxPatch((x,0.55),1.18,0.9,boxstyle='round,pad=0.06',fc=c,alpha=.16,ec=c,lw=1.6))\n"
         "    ax.text(x+0.59,1.0,s,ha='center',va='center',fontsize=10,fontweight='bold',color=c)\n"
         "    if i<8: ax.annotate('',(x+1.42,1.0),(x+1.22,1.0),arrowprops=dict(arrowstyle='->',color='.45'))\n"
         "ax.text(0.25,0.12,'OUF dataset(s) in',fontsize=9,color='.35')\n"
         "ax.text(11.0,0.12,'→ MeasurementSet out (no cosmology)',fontsize=9,color='.35')\n"
         "ax.set_title('the P1 → P2 preparation pipeline'); plt.show()"),
    md("## Galaxy clustering on real eBOSS\n"
       "Catalog + FKP weights + generated randoms + n(z) + footprint + shared "
       "jackknife regions — and the statistical checks that the selection "
       "model is faithful."),
    code(LOADQSO + "\n" + TO_OUF + "\n"
         "from oneuniverse.combine.weights import FKPWeight\n"
         "from oneuniverse import measure\n"
         "from scipy import stats\n"
         "eb,real = load_qso('eboss_qso', cap=50000, seed=1)\n"
         "view = to_ouf_view(eb, TMP, 'eboss')\n"
         "ms = measure.build_galaxy_clustering(view, tracer='qso', z_range=(0.8,2.2),\n"
         "    weights=[FKPWeight(nbar=lambda z: np.full_like(z,1e-3), P0=1e4)],\n"
         "    nside_window=64, nside_region=16, nz_edges=np.linspace(0.7,2.3,33),\n"
         "    randoms='generate', n_randoms=3*len(eb), seed=1)\n"
         "ps=ms.products['qso']; cat,rnd,nz=ps.catalog,ps.randoms,ps.nz\n"
         "ks=stats.ks_2samp(cat['z'],rnd['z'])\n"
         "fig,ax=plt.subplots(1,3,figsize=(14.5,4))\n"
         "ax[0].scatter(rnd['ra'][::6],rnd['dec'][::6],s=.25,c='.8')\n"
         "ax[0].scatter(cat['ra'][::3],cat['dec'][::3],s=.4,c=C0)\n"
         "ax[0].set_title(('REAL eBOSS' if real else 'synthetic')+' footprint + randoms')\n"
         "ax[0].set_xlabel('RA'); ax[0].set_ylabel('Dec')\n"
         "ax[1].hist(cat['z'],bins=nz.edges,density=True,histtype='step',lw=2.2,color=C0,label='data')\n"
         "ax[1].hist(rnd['z'],bins=nz.edges,density=True,histtype='step',lw=2.2,color=C1,label='randoms')\n"
         "ax[1].set_title(f'radial selection — KS p = {ks.pvalue:.2f}'); ax[1].set_xlabel('z'); ax[1].legend()\n"
         "sc=ax[2].scatter(cat['ra'][::3],cat['dec'][::3],s=.5,c=cat['region_id'][::3],cmap='tab20')\n"
         "ax[2].set_title(f\"{cat['region_id'].nunique()} shared jackknife regions\")\n"
         "ax[2].set_xlabel('RA'); ax[2].set_ylabel('Dec')\n"
         "plt.tight_layout(); plt.show()\n"
         "ms.check_invariants(); print('invariants OK | covered sky fraction %.3f' % ps.window.covered_fraction())"),
    md("## Weak lensing: shapes + the photo-z kernel\n"
       "The source PointSet carries ellipticities with metacal calibration and "
       "the full **per-object p(z) kernel** — shown as a waterfall, sorted by "
       "mean redshift — which stacks into the tomographic n(z)."),
    code("from fixtures.measure_ouf import synthetic_shear_view\n"
         "sv = synthetic_shear_view(TMP, n=6000, seed=3, kind='metacal', with_pdf=True, n_tomo=3, name='src')\n"
         "wl = measure.build_cosmic_shear(sv, tomo_column='tomo_bin', z_grid=np.linspace(0,2,61), nside_region=8)\n"
         "src=wl.products['src']; pz=src.photoz\n"
         "order=np.argsort(pz.mean()); V=np.asarray(pz.values)[order][::12]\n"
         "fig,ax=plt.subplots(1,3,figsize=(14.5,4))\n"
         "ax[0].imshow(V,aspect='auto',origin='lower',extent=[pz.grid[0],pz.grid[-1],0,len(V)],cmap='magma')\n"
         "ax[0].set_xlabel('z'); ax[0].set_ylabel('objects (sorted by ⟨z⟩)')\n"
         "ax[0].set_title('per-object photo-z kernels p(z)')\n"
         "for b,n in sorted(src.nz.items()): ax[1].plot(n.centers(),n.pdf(),lw=2.4,label=f'bin {b}')\n"
         "ax[1].set_title('stacked → tomographic n(z)'); ax[1].set_xlabel('z'); ax[1].legend()\n"
         "s=src.catalog.iloc[::18]; emag=np.hypot(s['e1'],s['e2']); ang=.5*np.arctan2(s['e2'],s['e1'])\n"
         "ax[2].quiver(s['ra'],s['dec'],emag*np.cos(ang),emag*np.sin(ang),headwidth=0,headlength=0,pivot='mid',scale=8,width=.003,color=C4)\n"
         "ax[2].set_title('shear whiskers (e1,e2 + metacal)'); ax[2].set_xlabel('RA'); ax[2].set_ylabel('Dec')\n"
         "plt.tight_layout(); plt.show()\n"
         "print('shape columns carried:', src.attributes['shapes'])"),
    md("## The probe gallery — one container, six builders"),
    code("from fixtures.measure_ouf import (synthetic_pv_view, synthetic_sn_view,\n"
         "    synthetic_sightline_view, synthetic_healpix_map, synthetic_point_view)\n"
         "from oneuniverse.measure.fieldmap import fieldmap_from_healpix\n"
         "pv=measure.build_peculiar_velocity(synthetic_pv_view(TMP,n=2500,seed=3,name='pv'),z_range=(0,0.1),nside_region=8)\n"
         "snv,_=synthetic_sn_view(TMP,n=350,seed=4,name='sn'); sn=measure.build_sn_hubble(snv,nside_region=4)\n"
         "lya=measure.build_lya(synthetic_sightline_view(TMP,n_los=150,n_pix=55,seed=2,name='lya'),nside_region=8)\n"
         "vals,mask=synthetic_healpix_map(nside=64,seed=4)\n"
         "fm=fieldmap_from_healpix(vals,mask=mask,nside=64,dataset_id='cmbk')\n"
         "xc=measure.build_map_cross(synthetic_point_view(TMP,n=4000,seed=3,name='g2'),fm,nside_region=8,z_range=(0.1,1.0))\n"
         "fig,ax=plt.subplots(1,4,figsize=(15.5,3.6))\n"
         "p0=pv.products['pv'].catalog\n"
         "s0=ax[0].scatter(p0['ra'],p0['dec'],s=4,c=p0['v_pec'],cmap='coolwarm',vmin=-600,vmax=600)\n"
         "ax[0].set_title('peculiar velocities'); plt.colorbar(s0,ax=ax[0],fraction=.05)\n"
         "s1=sn.products['sn'].catalog\n"
         "ax[1].errorbar(s1['z'],s1['mu'],yerr=s1['mu_err'],fmt='.',ms=3.5,alpha=.6,elinewidth=.5,color=C1)\n"
         "ax[1].set_title('SN Ia Hubble diagram'); ax[1].set_xlabel('z'); ax[1].set_ylabel('μ')\n"
         "sl=lya.products['lya']\n"
         "for i in range(6): ax[2].plot(sl.delta[i]+i*1.1,lw=.8,color=C2)\n"
         "ax[2].set_title(f'Lyα δ_F  ({sl.n_sightlines} sightlines)'); ax[2].set_xlabel('pixel (λ)')\n"
         "patch=fm.values[:4096].reshape(64,64)\n"
         "ax[3].imshow(patch,cmap='coolwarm',vmin=-2.5,vmax=2.5); ax[3].axis('off')\n"
         "ax[3].set_title('FieldMap κ × galaxies → C_ℓ')\n"
         "plt.tight_layout(); plt.show()\n"
         "for nm,m in [('clustering',ms),('cosmic shear',wl),('pec. velocity',pv),('SN Ia',sn),('Lyα',lya),('gal×κ',xc)]:\n"
         "    s=m.summary(); kinds='+'.join(sorted({p['kind'] for p in s['products'].values()}))\n"
         "    print(f\"{nm:14s} family={s['spec']['estimator_family']:<10s} statistic={s['spec']['statistic']:<16s} {kinds}\")"),
    md("## Beyond the builders: the generality slots\n"
       "The container also expresses probes with no one-call builder yet — "
       "via **sub-object links** (here: strong-lens systems with time-delay "
       "payloads), **named weight components** kept separable, and a "
       "**covariance plan**."),
    code("from oneuniverse.measure import SubObjectLinks, CovariancePlan, assemble_named_weights\n"
         "from oneuniverse.combine.weights import ColumnWeight, FKPWeight\n"
         "rng=np.random.default_rng(7); n_sys=6\n"
         "links=SubObjectLinks(role='lens_image', parent_ids=np.repeat(np.arange(n_sys),4),\n"
         "    child_ids=np.arange(n_sys*4),\n"
         "    payload={'dt_days': rng.lognormal(2.5,0.9,n_sys*4)})\n"
         "cat2 = view.read().head(4000).copy(); cat2['w_cp']=1.0; cat2['w_sys']=rng.uniform(.9,1.1,len(cat2))\n"
         "cat2,nw = assemble_named_weights(cat2, {'fkp':FKPWeight(nbar=lambda z: np.full_like(z,1e-3),P0=1e4),\n"
         "                                        'cp':ColumnWeight('w_cp'),'sys':ColumnWeight('w_sys')})\n"
         "fig,ax=plt.subplots(1,3,figsize=(14.5,3.7))\n"
         "for s_ in range(n_sys):\n"
         "    dts=links.payload['dt_days'][links.parent_ids==s_]\n"
         "    ax[0].scatter(np.full(4,s_),dts,s=22,c=C4); ax[0].plot([s_,s_],[dts.min(),dts.max()],c=C4,lw=1)\n"
         "ax[0].set_xlabel('lens system'); ax[0].set_ylabel('time delay Δt [days]'); ax[0].set_yscale('log')\n"
         "ax[0].set_title('SubObjectLinks: system → images (+Δt payload)')\n"
         "comps=list(nw.components); means=[nw.components[c].mean() for c in comps]\n"
         "ax[1].bar(comps,means,color=[C3,C0,C2]); ax[1].set_title('named weight components (kept separable)')\n"
         "ax[1].set_ylabel('mean weight')\n"
         "ax[2].axis('off')\n"
         "plan=CovariancePlan(kind='jackknife',region_nside=16)\n"
         "ax[2].text(.05,.8,'CovariancePlan',fontsize=12,fontweight='bold',color=C1)\n"
         "ax[2].text(.05,.55,f'kind          = {plan.kind}',family='monospace')\n"
         "ax[2].text(.05,.4,f'region_nside  = {plan.region_nside}',family='monospace')\n"
         "ax[2].text(.05,.25,\"alternatives: mocks | analytic | external (BLOB)\",family='monospace',fontsize=8.5)\n"
         "ax[2].set_title('how the covariance will be built')\n"
         "plt.tight_layout(); plt.show()"),
    md("## The handoff: save → reload → SQL\n"
       "A `MeasurementSet` persists to a self-describing directory and "
       "round-trips losslessly; it also exports to SQLite."),
    code("ms.to_dir(TMP/'ms_eboss')\n"
         "from oneuniverse.measure import MeasurementSet\n"
         "back = MeasurementSet.from_dir(TMP/'ms_eboss'); back.check_invariants()\n"
         "same_cat = len(back.products['qso'].catalog)==len(cat)\n"
         "same_nz = np.allclose(back.products['qso'].nz.counts, nz.counts)\n"
         "db = ms.to_sql(TMP/'ms.sqlite')\n"
         "tabs=[r[0] for r in sqlite3.connect(db).execute(\"SELECT name FROM sqlite_master WHERE type='table'\")]\n"
         "print('round-trip: catalog rows equal:',same_cat,'| n(z) equal:',same_nz)\n"
         "print('SQL tables:',tabs)\n"
         "print('summary is JSON-safe:', bool(json.dumps(back.summary())))"),
    md("**What this showed.** One pipeline, one container: real-survey "
       "clustering with verifiable selection modelling, lensing with the full "
       "photo-z kernel, a four-probe gallery, the generality slots that cover "
       "builder-less probes, and a handoff that survives disk, relocation and "
       "SQL — all without a single cosmological assumption."),
])

# ════════════════════════════════════════════════════════════════════════
# 04 — Simulation storage at scale
# ════════════════════════════════════════════════════════════════════════
save("04_simulation_store.ipynb", [
    md("# 04 · Simulation storage — query terabytes, copy nothing\n"
       "*OUF-Sim: manifest + spatial index + partial access, with a "
       "wrap-in-place mode that stores only an index over native files.*\n\n"
       "Claims demonstrated: (i) a box read touches only overlapping chunks; "
       "(ii) **wrap-in-place** keeps ~13% of the re-encoded size by indexing "
       "the native files instead of copying them; (iii) storage is lossless — "
       "the stored field's P(k) matches the input to round-off."),
    code(SETUP + "\n" + PK),
    md("## Build a store, read a sub-box, see the pruning"),
    code("from oneuniverse.simulation.linear import generate_linear_sim\n"
         "from oneuniverse.simulation.linear.pack import write_packed_native\n"
         "from oneuniverse.simulation.packed.converter import PackedSimConverter\n"
         "from oneuniverse.simulation.oufsim import SimStore\n"
         "from oneuniverse.simulation.selectors import Cube\n"
         "BOX,N=400.0,64\n"
         "lin=generate_linear_sim(TMP/'lin',COSMO,box_size=BOX,n_grid=N,redshifts=(0.0,),seed=2,with_lightcone=False)\n"
         "pk_native=write_packed_native(lin,TMP/'pk',particle_chunk_nside=4)\n"
         "enc=PackedSimConverter().convert(pk_native,TMP/'enc',sim_name='d',projection='reencode')\n"
         "ref=PackedSimConverter().convert(pk_native,TMP/'ref',sim_name='e',projection='reference')\n"
         "store=SimStore(enc)\n"
         "cube=Cube(0,BOX/4,0,BOX/4,0,BOX/4)\n"
         "sub=store.read_box('snapshots',0.0,cube); st=store.last_read_stats\n"
         "fig,ax=plt.subplots(1,2,figsize=(12.5,5))\n"
         "import pyarrow.parquet as pq_\n"
         "idx=pq_.read_table(Path(enc)/'snapshots'/'z0.000'/'_index.parquet').to_pandas()\n"
         "norm=plt.Normalize(idx['n_rows'].min(),idx['n_rows'].max())\n"
         "for _,r in idx.iterrows():\n"
         "    hitc = not (r['xhi']<cube.xlo or r['xlo']>cube.xhi or r['yhi']<cube.ylo or r['ylo']>cube.yhi or r['zhi']<cube.zlo or r['zlo']>cube.zhi)\n"
         "    ax[0].add_patch(Rectangle((r['xlo'],r['ylo']),r['xhi']-r['xlo'],r['yhi']-r['ylo'],\n"
         "        fc=plt.cm.viridis(norm(r['n_rows'])),ec=(C1 if hitc else 'white'),lw=(2.4 if hitc else .5),alpha=.85))\n"
         "ax[0].add_patch(Rectangle((cube.xlo,cube.ylo),cube.xhi-cube.xlo,cube.yhi-cube.ylo,fill=False,ec=C1,lw=3,ls='--'))\n"
         "ax[0].set_xlim(0,BOX); ax[0].set_ylim(0,BOX); ax[0].set_xlabel('x [Mpc/h]'); ax[0].set_ylabel('y [Mpc/h]')\n"
         "ax[0].set_title(f\"chunk index + requested box — read {st['chunks_read']}/{st['chunks_total']} chunks\")\n"
         "ax[1].scatter(sub['x'][::5],sub['y'][::5],s=.6,c=C0,alpha=.6)\n"
         "ax[1].set_xlim(0,BOX); ax[1].set_ylim(0,BOX); ax[1].set_title(f\"{len(sub['x']):,} particles returned\")\n"
         "ax[1].set_xlabel('x [Mpc/h]'); plt.tight_layout(); plt.show()"),
    md("## Wrap-in-place vs re-encode — and the byte-range index\n"
       "The `reference` projection stores **no particle data** — only per-"
       "chunk `[row_start, row_stop)` ranges into the native, spatially-sorted "
       "file. Left: store sizes. Right: the actual byte-range map."),
    code("size=lambda p: sum(f.stat().st_size for f in Path(p).rglob('*') if f.is_file())/1e6\n"
         "idx_ref=pq_.read_table(Path(ref)/'snapshots'/'z0.000'/'_index.parquet').to_pandas()\n"
         "fig,ax=plt.subplots(1,2,figsize=(12.5,4.2))\n"
         "vals=[size(pk_native),size(ref),size(enc)]\n"
         "bars=ax[0].bar(['native files','wrap-in-place\\n(index only)','re-encode\\n(full copy)'],vals,color=[C3,C2,C0])\n"
         "for b,v in zip(bars,vals): ax[0].text(b.get_x()+b.get_width()/2,v+.3,f'{v:.1f} MB',ha='center',fontsize=9.5)\n"
         "ax[0].set_ylabel('size [MB]'); ax[0].set_title(f'storage: wrap = {100*vals[1]/vals[2]:.0f}% of re-encode')\n"
         "y=np.arange(len(idx_ref))\n"
         "ax[1].barh(y, idx_ref['row_stop']-idx_ref['row_start'], left=idx_ref['row_start'], height=.8, color=C2, alpha=.8)\n"
         "ax[1].set_xlabel('row range in the NATIVE particle file'); ax[1].set_ylabel('chunk id')\n"
         "ax[1].set_title('wrap-in-place = an index of byte ranges, zero copies')\n"
         "plt.tight_layout(); plt.show()"),
    md("## Lossless: P(k) of the stored field == input field"),
    code("from oneuniverse.simulation.linear.gaussian_field import generate_density_field\n"
         "orig=generate_density_field(COSMO,box_size=BOX,n_grid=N,z=0.0,seed=2)\n"
         "stored,_=store.read_field_box(0.0,Cube(0,BOX,0,BOX,0,BOX))\n"
         "kny=np.pi*N/BOX; edges=np.logspace(np.log10(2*np.pi/BOX*1.5),np.log10(.7*kny),14)\n"
         "k1,P1,E1=measure_pk(orig,BOX,edges); k2,P2,_=measure_pk(np.asarray(stored),BOX,edges)\n"
         "fig,ax=plt.subplots(1,2,figsize=(12.5,4))\n"
         "ax[0].errorbar(k1,P1,yerr=E1,fmt='o',color=C0,label='in-memory'); ax[0].plot(k2,P2,'x--',color=C1,label='read from store')\n"
         "ax[0].set_xscale('log'); ax[0].set_yscale('log'); ax[0].set_xlabel('k [h/Mpc]'); ax[0].set_ylabel('P(k)'); ax[0].legend()\n"
         "ax[0].set_title('stored vs original power spectrum')\n"
         "ax[1].plot(k1,P2/P1,'o-',color=C2); ax[1].axhline(1,color=C1,ls='--'); ax[1].set_xscale('log')\n"
         "ax[1].set_ylim(.999,1.001); ax[1].set_xlabel('k [h/Mpc]'); ax[1].set_ylabel('stored / original')\n"
         "ax[1].set_title(f'max deviation: {np.max(np.abs(P2/P1-1)):.1e}')\n"
         "plt.tight_layout(); plt.show()"),
    md("## It scales: index-only storage stays index-sized"),
    code("from oneuniverse.simulation.oufsim.scale_bench import sweep\n"
         "rows=sweep(TMP/'sw',COSMO,grids=(32,48,64),box=BOX)\n"
         "npart=[r['n_particles'] for r in rows]\n"
         "fig,ax=plt.subplots(1,2,figsize=(12.5,4))\n"
         "x=np.arange(len(rows)); w=.26\n"
         "ax[0].bar(x-w,[r['native_mb'] for r in rows],w,label='native',color=C3)\n"
         "ax[0].bar(x,[r['store_reference_mb'] for r in rows],w,label='wrap-in-place',color=C2)\n"
         "ax[0].bar(x+w,[r['store_reencode_mb'] for r in rows],w,label='re-encode',color=C0)\n"
         "ax[0].set_xticks(x); ax[0].set_xticklabels([f\"{r['n_grid']}³\" for r in rows])\n"
         "ax[0].set_ylabel('MB'); ax[0].legend(); ax[0].set_title('storage vs simulation size')\n"
         "ax[1].plot(npart,[r['convert_peak_mb'] for r in rows],'o-',color=C4)\n"
         "ax[1].set_xlabel('particles'); ax[1].set_ylabel('peak memory [MB]')\n"
         "ax[1].set_title('bounded conversion memory'); plt.tight_layout(); plt.show()\n"
         "print('wrap fraction of re-encode:', ['%.0f%%'%(100*r['store_reference_mb']/r['store_reencode_mb']) for r in rows])"),
    md("**What this showed.** A spatial chunk index that prunes box reads to "
       "the overlapping chunks; a wrap-in-place projection that is literally "
       "an index of byte ranges over the native files (~13% of a copy); "
       "bit-lossless field storage; and bounded conversion memory as the "
       "simulation grows. The *physics* stored here is a linear toy — the "
       "storage machinery is the real deliverable."),
])
