# Notebooks 01 (data) + 02 (SQL) — executed by _build_notebooks.py.

# ════════════════════════════════════════════════════════════════════════
# 01 — One universe of data
# ════════════════════════════════════════════════════════════════════════
save("01_one_universe_of_data.ipynb", [
    md("# 01 · One universe of data\n"
       "*Heterogeneous surveys → one standard, queryable, cosmology-free "
       "database.*\n\n"
       "Every survey ships its own FITS layout, column names and conventions. "
       "`oneuniverse.data` collapses them onto one schema and one on-disk "
       "format — **OUF 2.6**: an identity-only `manifest.json` + a parquet "
       "**partition index sidecar** + HEALPix-partitioned data. This notebook "
       "shows, on the **real eBOSS DR16Q and DESI DR1 quasar catalogs**: the "
       "shared sky, cross-survey identity, the anatomy of the format, and why "
       "partial access makes a 2-million-row catalog feel small."),
    code(SETUP),
    code(LOADQSO + "\neb,_ = load_qso('eboss_qso', cap=60000, seed=1)\n"
         "de,real = load_qso('desi_qso', cap=60000, seed=2)\n"
         "print(('REAL data' if real else 'synthetic stand-in'),\n"
         "      '| eBOSS rows:',len(eb),'| DESI rows:',len(de))"),
    md("## The same sky, two instruments\n"
       "Mollweide view of both quasar samples — the NGC/SGC geometry of "
       "eBOSS against DESI's wider footprint, plus their redshift selections."),
    code("fig = plt.figure(figsize=(13,5.4))\n"
         "ax1 = fig.add_subplot(1,2,1, projection='mollweide')\n"
         "moll(ax1, eb['ra'][::6], eb['dec'][::6], s=.4, c=C0, alpha=.5, label='eBOSS DR16Q')\n"
         "moll(ax1, de['ra'][::6], de['dec'][::6], s=.4, c=C1, alpha=.35, label='DESI DR1 QSO')\n"
         "ax1.grid(alpha=.3); ax1.set_xticklabels([]); ax1.set_title('two real quasar surveys, one sky')\n"
         "ax1.legend(markerscale=14, loc='lower right', fontsize=9)\n"
         "ax2 = fig.add_subplot(1,2,2)\n"
         "bins=np.linspace(0.8,2.2,40)\n"
         "ax2.hist(eb['z'],bins=bins,density=True,histtype='stepfilled',alpha=.45,color=C0,label='eBOSS')\n"
         "ax2.hist(de['z'],bins=bins,density=True,histtype='stepfilled',alpha=.45,color=C1,label='DESI')\n"
         "ax2.set_xlabel('redshift z'); ax2.set_ylabel('n(z) (normalised)')\n"
         "ax2.set_title('redshift selections'); ax2.legend()\n"
         "plt.tight_layout(); plt.show()"),
    md("## Cross-survey identity\n"
       "The same quasar appears in both surveys. A positional match shows the "
       "genuine-repeat peak at sub-arcsecond separations over a flat chance-"
       "alignment background — the geometric core of the package's **ONEUID** "
       "bitemporal cross-match."),
    code("from scipy.spatial import cKDTree\n"
         "def unit(ra,dec):\n"
         "    r=np.radians(ra); d=np.radians(dec)\n"
         "    return np.c_[np.cos(d)*np.cos(r), np.cos(d)*np.sin(r), np.sin(d)]\n"
         "tree=cKDTree(unit(de['ra'].to_numpy(),de['dec'].to_numpy()))\n"
         "dist,_=tree.query(unit(eb['ra'].to_numpy(),eb['dec'].to_numpy()),k=1)\n"
         "sep=np.degrees(2*np.arcsin(np.clip(dist/2,0,1)))*3600\n"
         "fig,ax=plt.subplots(1,2,figsize=(12.5,4))\n"
         "ax[0].hist(sep[sep<8],bins=80,color=C4)\n"
         "ax[0].axvline(1.5,color=C1,ls='--',lw=2,label='1.5\" match radius')\n"
         "ax[0].set_xlabel('nearest-neighbour separation [arcsec]'); ax[0].set_ylabel('pairs')\n"
         "ax[0].set_title('eBOSS ↔ DESI: genuine repeats vs chance'); ax[0].legend()\n"
         "ss=np.sort(sep); ax[1].plot(ss, np.arange(1,len(ss)+1)/len(ss)*100, c=C4, lw=2)\n"
         "ax[1].set_xlim(0,30); ax[1].set_xlabel('match radius [arcsec]')\n"
         "ax[1].set_ylabel('% of eBOSS QSOs matched'); ax[1].set_title('cumulative match fraction')\n"
         "ax[1].axvline(1.5,color=C1,ls='--'); plt.tight_layout(); plt.show()\n"
         "print(f'matched within 1.5\": {(sep<1.5).sum():,} of {len(sep):,} ({100*(sep<1.5).mean():.1f}%)')"),
    md("## Anatomy of OUF 2.6\n"
       "Convert the eBOSS sample to OUF and dissect it: the **identity-only "
       "manifest** (stable JSON, no bulk), the **partition-index sidecar** "
       "(`_index.parquet`, one row per HEALPix partition with its file, row "
       "count and z-range), and the partitions painted on the sky."),
    code(TO_OUF + "\nview = to_ouf_view(eb, TMP, 'eboss')\n"
         "ou = view.ou_dir\n"
         "raw = json.loads((ou/'manifest.json').read_text())\n"
         "import pyarrow.parquet as pq\n"
         "idx = pq.read_table(ou/'_index.parquet').to_pandas()\n"
         "fig = plt.figure(figsize=(13.5,4.6))\n"
         "axA = fig.add_subplot(1,3,1); axA.axis('off')\n"
         "tree = ('{survey}/oneuniverse/\\n'\n"
         "        ' ├─ manifest.json        identity only\\n'\n"
         "        f\" │    format {raw['oneuniverse_format_version']}, geometry {raw['geometry']}\\n\"\n"
         "        f\" │    n_partitions {raw['n_partitions']}, n_rows {raw['n_rows_total']:,}\\n\"\n"
         "        ' ├─ _index.parquet       partition stats sidecar\\n'\n"
         "        ' └─ data/healpix32=N/    the rows themselves')\n"
         "axA.text(0.0,0.95,tree,family='monospace',fontsize=9.5,va='top')\n"
         "axA.set_title('on-disk anatomy (OUF 2.6)')\n"
         "axB = fig.add_subplot(1,3,2); axB.axis('off')\n"
         "head = idx[['healpix_cell','n_rows','z_min','z_max']].head(8).round(3)\n"
         "tb=axB.table(cellText=head.values, colLabels=head.columns, loc='center')\n"
         "tb.scale(1,1.45); tb.auto_set_font_size(False); tb.set_fontsize(8.5)\n"
         "axB.set_title('_index.parquet (first rows)')\n"
         "axC = fig.add_subplot(1,3,3)\n"
         "cells = idx['healpix_cell'].to_numpy(); nr = idx['n_rows'].to_numpy()\n"
         "th,ph = hp.pix2ang(32, cells.astype(int), nest=True)\n"
         "sc=moll if False else None\n"
         "lon = np.radians(((np.degrees(ph)+180)%360)-180)\n"
         "s=axC.scatter(np.degrees(ph), 90-np.degrees(th), c=nr, s=18, cmap='viridis')\n"
         "axC.set_xlabel('RA [deg]'); axC.set_ylabel('Dec [deg]')\n"
         "axC.set_title('partitions on the sky (colour = rows)')\n"
         "plt.colorbar(s, ax=axC, fraction=.05)\n"
         "plt.tight_layout(); plt.show()\n"
         "print('manifest keys:', sorted(k for k in raw if not k.startswith('_'))[:9], '…')"),
    md("## Partial access: read only what you ask for\n"
       "The reader resolves a selector against the sidecar index and touches "
       "only the overlapping partitions."),
    code("from oneuniverse.data.selection import Cone\n"
         "cra,cdec = float(eb['ra'].median()), float(eb['dec'].median())\n"
         "jobs = {'full catalog': dict(), '12° cone': dict(cone=Cone(ra=cra,dec=cdec,radius=12)),\n"
         "        'z ∈ [1.0,1.2]': dict(z_range=(1.0,1.2)),\n"
         "        'cone + z cut': dict(cone=Cone(ra=cra,dec=cdec,radius=12), z_range=(1.0,1.2))}\n"
         "rows=[]; times=[]\n"
         "for name,kw in jobs.items():\n"
         "    t0=time.perf_counter(); d=view.read(columns=['ra','dec','z'],**kw)\n"
         "    times.append(1e3*(time.perf_counter()-t0)); rows.append(len(d))\n"
         "fig,ax=plt.subplots(1,2,figsize=(12.5,3.8))\n"
         "y=np.arange(len(jobs))\n"
         "ax[0].barh(y,rows,color=[C0,C2,C3,C1]); ax[0].set_yticks(y); ax[0].set_yticklabels(jobs)\n"
         "ax[0].set_xlabel('rows returned'); ax[0].set_title('selector → rows')\n"
         "ax[1].barh(y,times,color=[C0,C2,C3,C1]); ax[1].set_yticks(y); ax[1].set_yticklabels([])\n"
         "ax[1].set_xlabel('wall time [ms]'); ax[1].set_title('selector → time')\n"
         "plt.tight_layout(); plt.show()\n"
         "for (n,_),r,t in zip(jobs.items(),rows,times): print(f'{n:14s} {r:7,} rows  {t:6.1f} ms')"),
    md("**What this showed.** Two real surveys on one schema; the same quasars "
       "re-identified across them at sub-arcsecond precision; an on-disk "
       "format whose manifest is identity-only with a queryable partition "
       "sidecar; and selector-driven reads that scale with the question, not "
       "the catalog. No cosmology touched the data at any point."),
])

# ════════════════════════════════════════════════════════════════════════
# 02 — The SQL face
# ════════════════════════════════════════════════════════════════════════
save("02_sql_database.ipynb", [
    md("# 02 · The SQL face of both databases\n"
       "*Everything exports to standard SQL — the most portable analysis "
       "surface there is.*\n\n"
       "`oneuniverse` can materialise its two on-disk formats into **SQLite** "
       "(stdlib, single portable file) or generate **zero-copy DuckDB views** "
       "over the existing parquet. The design mirrors the package's own "
       "storage philosophy: *materialise* ≡ re-encode, *attach* ≡ "
       "wrap-in-place. Real eBOSS data throughout."),
    code(SETUP),
    md("## The schema at a glance"),
    code("fig,ax=plt.subplots(figsize=(12.5,4.6)); ax.axis('off'); ax.set_xlim(0,12); ax.set_ylim(0,6)\n"
         "def box(x,y,w,h,title,rows,color):\n"
         "    ax.add_patch(FancyBboxPatch((x,y),w,h,boxstyle='round,pad=0.07',fc=color,alpha=.14,ec=color,lw=1.6))\n"
         "    ax.text(x+w/2,y+h-0.28,title,ha='center',fontsize=10,fontweight='bold',color=color)\n"
         "    ax.text(x+0.12,y+h-0.62,rows,fontsize=8.2,va='top',family='monospace')\n"
         "box(0.2,3.3,2.7,2.4,'datasets','survey_name\\nsurvey_type\\ngeometry\\nformat_version\\nmanifest_json',C0)\n"
         "box(3.3,3.3,2.7,2.4,'objects','dataset_id→\\nra, dec, z\\ngalaxy_id\\nhealpix32 ⌕\\nextra JSON',C0)\n"
         "box(6.4,3.3,2.6,2.4,'pdf_payloads','dataset_id→\\ngalaxy_id→\\npdf_values BLOB\\n(float32, exact)',C0)\n"
         "box(9.3,3.3,2.5,2.4,'oneuid_members','run_id→\\noneuid ⌕\\ndataset\\nrow_index',C4)\n"
         "box(0.2,0.3,2.7,2.4,'sims','sim_name\\nbox_size, n_grid\\ncosmology_json\\nmanifest_json',C2)\n"
         "box(3.3,0.3,2.7,2.4,'sim_chunks','product, z\\nbbox xlo..zhi ⌕\\nfile / native_file\\nrow_start..stop',C2)\n"
         "box(6.4,0.3,2.6,2.4,'halos / lightcone','materialised\\n(catalog-sized\\nproducts only)',C2)\n"
         "box(9.3,0.3,2.5,2.4,'measurement_sets','family, statistic\\nsummary_json\\ncatalog_<t>\\nrandoms_<t>',C1)\n"
         "ax.annotate('',(3.3,4.5),(2.9,4.5),arrowprops=dict(arrowstyle='->',color='.4'))\n"
         "ax.annotate('',(6.4,4.5),(6.0,4.5),arrowprops=dict(arrowstyle='->',color='.4'))\n"
         "ax.annotate('',(3.3,1.5),(2.9,1.5),arrowprops=dict(arrowstyle='->',color='.4'))\n"
         "ax.text(0.2,5.85,'OUF → catalog.sqlite',fontsize=11,fontweight='bold',color=C0)\n"
         "ax.text(0.2,2.85,'OUF-Sim → sim.sqlite',fontsize=11,fontweight='bold',color=C2)\n"
         "ax.set_title('the exported SQL schema (⌕ = indexed)'); plt.show()"),
    md("## Real eBOSS → `catalog.sqlite`, queried in pure SQL\n"
       "Export, then answer survey questions with SQL alone: a z-histogram by "
       "`GROUP BY`, and a sky cone as a HEALPix `WHERE IN` — the package's "
       "partition pruning, expressed relationally."),
    code(LOADQSO + "\n" + TO_OUF + "\n"
         "from oneuniverse.data.sql import export_sql, attach_sql_ddl\n"
         "eb,real = load_qso('eboss_qso', cap=50000, seed=1)\n"
         "view = to_ouf_view(eb, TMP, 'eboss')\n"
         "t0=time.perf_counter(); db = export_sql([view], TMP/'catalog.sqlite'); t_exp=time.perf_counter()-t0\n"
         "con = sqlite3.connect(db)\n"
         "print(f'exported {len(eb):,} real rows -> {db.name} ({db.stat().st_size/1e6:.1f} MB) in {t_exp:.1f}s')\n"
         "zh = pd.read_sql_query('SELECT ROUND(z,1) zb, COUNT(*) n FROM objects GROUP BY zb ORDER BY zb', con)\n"
         "cra,cdec=float(eb['ra'].median()),float(eb['dec'].median())\n"
         "vec=hp.ang2vec(np.radians(90-cdec),np.radians(cra))\n"
         "pix=hp.query_disc(32,vec,np.radians(8.0),nest=True,inclusive=True)\n"
         "q=','.join('?'*len(pix))\n"
         "cone=pd.read_sql_query(f'SELECT ra,dec FROM objects WHERE healpix32 IN ({q})',con,params=[int(p) for p in pix])\n"
         "fig,ax=plt.subplots(1,2,figsize=(12.5,4))\n"
         "ax[0].bar(zh['zb'],zh['n'],width=.085,color=C0)\n"
         "ax[0].set_xlabel('z (0.1 bins)'); ax[0].set_ylabel('QSOs'); ax[0].set_title('SQL: SELECT ROUND(z,.1), COUNT(*) … GROUP BY')\n"
         "ax[1].scatter(eb['ra'][::4],eb['dec'][::4],s=.4,c='.8')\n"
         "ax[1].scatter(cone['ra'],cone['dec'],s=.8,c=C1)\n"
         "ax[1].set_xlabel('RA'); ax[1].set_ylabel('Dec'); ax[1].set_title(f'SQL cone: healpix32 IN (…)  → {len(cone):,} rows')\n"
         "plt.tight_layout(); plt.show()"),
    md("## ONEUID in SQL — the cross-match becomes a JOIN\n"
       "The bitemporal cross-match exports as `oneuid_runs` + `oneuid_members`; "
       "`as_of` queries become WHERE clauses on `built_utc/archived_utc`."),
    code("from oneuniverse.data.sql import export_oneuid\n"
         "members = pd.DataFrame({'oneuid':[0,0,1,1,2],\n"
         "    'dataset':['eboss','desi','eboss','desi','eboss'],\n"
         "    'row_index':[10,55,11,77,12]})\n"
         "export_oneuid(con, members, name='eboss_x_desi', rules_json='{\"sky_tol_arcsec\":1.5}')\n"
         "j = pd.read_sql_query(\n"
         "    'SELECT m.oneuid, m.dataset, m.row_index FROM oneuid_members m '\n"
         "    'JOIN oneuid_runs r ON r.run_id=m.run_id '\n"
         "    'WHERE r.archived_utc IS NULL ORDER BY m.oneuid', con)\n"
         "print('one object = one oneuid across surveys:'); print(j.to_string(index=False))\n"
         "n_multi = con.execute('SELECT COUNT(*) FROM (SELECT oneuid FROM oneuid_members '\n"
         "                      'GROUP BY oneuid HAVING COUNT(DISTINCT dataset)>1)').fetchone()[0]\n"
         "print(f'objects seen by BOTH surveys: {n_multi}')"),
    md("## OUF-Sim → `sim.sqlite`: the chunk index is a table\n"
       "Bulk products stay index-only — SQL answers *which file/byte-range "
       "holds box X*. The bbox query returns exactly the chunks the native "
       "reader touches (tested parity)."),
    code("from oneuniverse.simulation.linear import generate_linear_sim\n"
         "from oneuniverse.simulation.oufsim import write_oufsim_store\n"
         "from oneuniverse.simulation.oufsim.sql import export_sim_sql\n"
         "lin=generate_linear_sim(TMP/'lin',COSMO,box_size=200.,n_grid=32,redshifts=(0.,),seed=2)\n"
         "store=write_oufsim_store(lin,TMP/'st',sim_name='demo',particle_chunk_nside=4)\n"
         "sdb=export_sim_sql(store,TMP/'sim.sqlite'); scon=sqlite3.connect(sdb)\n"
         "ch=pd.read_sql_query(\"SELECT chunk_id,xlo,xhi,ylo,yhi,n_rows FROM sim_chunks \"\n"
         "                     \"WHERE product='snapshots' AND z=0.0\", scon)\n"
         "qx=(0,60); qy=(0,60)\n"
         "hit=pd.read_sql_query(\"SELECT chunk_id FROM sim_chunks WHERE product='snapshots' AND z=0.0 \"\n"
         "    \"AND NOT (xhi<? OR xlo>? OR yhi<? OR ylo>? OR zhi<0 OR zlo>60)\", scon,\n"
         "    params=[qx[0],qx[1],qy[0],qy[1]])['chunk_id'].tolist()\n"
         "fig,ax=plt.subplots(figsize=(6.6,5.6))\n"
         "norm=plt.Normalize(ch['n_rows'].min(),ch['n_rows'].max())\n"
         "for _,r in ch.iterrows():\n"
         "    sel = r['chunk_id'] in hit\n"
         "    ax.add_patch(Rectangle((r['xlo'],r['ylo']),r['xhi']-r['xlo'],r['yhi']-r['ylo'],\n"
         "        fc=plt.cm.viridis(norm(r['n_rows'])), ec=(C1 if sel else 'white'), lw=(2.2 if sel else .6), alpha=.85))\n"
         "ax.add_patch(Rectangle((qx[0],qy[0]),qx[1]-qx[0],qy[1]-qy[0],fill=False,ec=C1,lw=3,ls='--'))\n"
         "ax.set_xlim(0,200); ax.set_ylim(0,200); ax.set_xlabel('x [Mpc/h]'); ax.set_ylabel('y [Mpc/h]')\n"
         "ax.set_title(f'sim_chunks in SQL — bbox query hits {len(hit)} chunks (red)')\n"
         "plt.colorbar(plt.cm.ScalarMappable(norm=norm,cmap='viridis'),ax=ax,label='particles/chunk')\n"
         "plt.show()\n"
         "print(pd.read_sql_query('SELECT product, COUNT(*) chunks, SUM(n_rows) rows_indexed '\n"
         "                        'FROM sim_chunks GROUP BY product', scon).to_string(index=False))"),
    md("## Zero-copy mode\n"
       "For huge catalogs, don't copy at all: generated DuckDB views read the "
       "existing parquet in place — the SQL face of *wrap-in-place*."),
    code("print(attach_sql_ddl([view]))\n"
         "con.close(); scon.close()"),
    md("**What this showed.** Both databases speak SQL: real-survey questions "
       "as `GROUP BY`/`WHERE IN`, the cross-match as a JOIN, the simulation "
       "chunk map as a relational bbox query, and a zero-copy DuckDB path when "
       "materialising is the wrong answer."),
])
