"""OUF → SQL export (SQLite materialise mode).

SQL is the lingua franca; this module turns one or more OUF datasets into a
single portable SQLite file with the schema designed in
``research/2026-06-10-structural-review-and-sql-design.md`` §5.2:

    datasets         one row per survey (manifest verbatim in manifest_json)
    partitions       the per-HEALPix-partition index (file, n_rows, z range)
    objects          one row per object, all surveys (dataset_id FK);
                     canonical columns typed, survey extras as JSON
    pdf_specs        per-dataset PDF parameterisation (JSON)
    pdf_payloads     per-object p(z) as raw float32 BLOBs (NOT normal form —
                     1000 bins x 1e8 objects as rows would be unusable)
    oneuid_runs /    the ONEUID cross-match, relational: bitemporality is
    oneuid_members   built_utc/archived_utc columns, `as_of` becomes SQL
    subobject_links  parent→child hierarchies with a role

Cosmology-free by construction — it copies OUF verbatim and OUF carries no
cosmology. Uses only the stdlib ``sqlite3`` (no new dependencies). The DuckDB
zero-copy ``attach`` mode (views over the existing parquet) is generated by
:func:`attach_sql_ddl`.
"""
from __future__ import annotations

import datetime as _dt
import json
import sqlite3
from pathlib import Path
from typing import Iterable, Optional, Sequence, Union

import numpy as np
import pandas as pd

from oneuniverse.data.dataset_view import DatasetView
from oneuniverse.data.format_spec import ONEUNIVERSE_SUBDIR

_CORE = ("ra", "dec", "z", "z_type", "z_err", "galaxy_id", "survey_id")

_DDL = """
CREATE TABLE IF NOT EXISTS datasets (
  dataset_id      INTEGER PRIMARY KEY,
  survey_name     TEXT UNIQUE NOT NULL,
  survey_type     TEXT NOT NULL,
  geometry        TEXT NOT NULL,
  format_version  TEXT NOT NULL,
  n_rows          INTEGER,
  manifest_json   TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS partitions (
  dataset_id INTEGER REFERENCES datasets(dataset_id),
  healpix32  INTEGER,
  file       TEXT NOT NULL,
  n_rows     INTEGER,
  z_min REAL, z_max REAL,
  PRIMARY KEY (dataset_id, file)
);
CREATE TABLE IF NOT EXISTS objects (
  dataset_id INTEGER REFERENCES datasets(dataset_id),
  galaxy_id  INTEGER NOT NULL,
  ra REAL NOT NULL, dec REAL NOT NULL,
  z REAL, z_type TEXT, z_err REAL,
  healpix32  INTEGER NOT NULL,
  extra      TEXT,
  PRIMARY KEY (dataset_id, galaxy_id)
);
CREATE INDEX IF NOT EXISTS idx_objects_hpx ON objects(healpix32);
CREATE INDEX IF NOT EXISTS idx_objects_z   ON objects(dataset_id, z);
CREATE TABLE IF NOT EXISTS pdf_specs (
  dataset_id INTEGER PRIMARY KEY REFERENCES datasets(dataset_id),
  spec_json  TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS pdf_payloads (
  dataset_id INTEGER, galaxy_id INTEGER,
  pdf_values BLOB NOT NULL,
  PRIMARY KEY (dataset_id, galaxy_id)
);
CREATE TABLE IF NOT EXISTS oneuid_runs (
  run_id INTEGER PRIMARY KEY,
  name TEXT NOT NULL, rules_json TEXT,
  built_utc TEXT NOT NULL, archived_utc TEXT
);
CREATE TABLE IF NOT EXISTS oneuid_members (
  run_id INTEGER REFERENCES oneuid_runs(run_id),
  oneuid INTEGER NOT NULL,
  dataset TEXT NOT NULL, row_index INTEGER NOT NULL,
  PRIMARY KEY (run_id, dataset, row_index)
);
CREATE INDEX IF NOT EXISTS idx_oneuid ON oneuid_members(run_id, oneuid);
CREATE TABLE IF NOT EXISTS subobject_links (
  name TEXT NOT NULL, relation_type TEXT NOT NULL,
  parent_oneuid INTEGER NOT NULL, child_oneuid INTEGER NOT NULL,
  confidence REAL, payload_json TEXT
);
"""


def _as_view(x) -> DatasetView:
    if isinstance(x, DatasetView):
        return x
    p = Path(x)
    if (p / ONEUNIVERSE_SUBDIR).is_dir():
        return DatasetView.from_path(p)
    return DatasetView.from_ou_dir(p)


def _scalar_extra_columns(df: pd.DataFrame) -> list:
    """Non-core scalar columns (survey extras). Array-valued columns (PDFs,
    spectra) are excluded — they go to typed BLOB tables, not JSON."""
    out = []
    for c in df.columns:
        if c in _CORE or c.startswith("_"):
            continue
        v = df[c].iloc[0] if len(df) else None
        if isinstance(v, (list, tuple, np.ndarray)):
            continue
        out.append(c)
    return out


def export_sql(sources: Iterable, out: Union[str, Path], *,
               include_pdfs: bool = True,
               chunk_rows: int = 50_000) -> Path:
    """Materialise OUF dataset(s) into one SQLite file. Returns its path.

    ``sources``: DatasetViews or survey paths. Objects are inserted in
    ``chunk_rows`` batches (bounded memory). Re-exporting an existing survey
    name raises (SQLite UNIQUE) rather than silently duplicating.
    """
    out = Path(out)
    con = sqlite3.connect(out)
    try:
        con.executescript(_DDL)
        for src in sources:
            view = _as_view(src)
            m = view.manifest
            raw = json.loads((view.ou_dir / "manifest.json").read_text())
            cur = con.execute(
                "INSERT INTO datasets (survey_name, survey_type, geometry,"
                " format_version, n_rows, manifest_json)"
                " VALUES (?,?,?,?,?,?)",
                (m.survey_name, m.survey_type, m.geometry.value,
                 m.oneuniverse_format_version, m.n_rows, json.dumps(raw)))
            ds_id = cur.lastrowid
            con.executemany(
                "INSERT INTO partitions VALUES (?,?,?,?,?,?)",
                [(ds_id, p.healpix_cell, p.name, p.n_rows,
                  p.stats.z_min, p.stats.z_max) for p in m.partitions])

            df = view.read()
            extras = _scalar_extra_columns(df)
            n = len(df)
            for lo in range(0, n, chunk_rows):
                part = df.iloc[lo:lo + chunk_rows]
                ex = (part[extras].apply(
                          lambda r: json.dumps(r.to_dict()), axis=1)
                      if extras else pd.Series([None] * len(part),
                                               index=part.index))
                con.executemany(
                    "INSERT INTO objects VALUES (?,?,?,?,?,?,?,?,?)",
                    zip([ds_id] * len(part),
                        part["galaxy_id"].astype(int),
                        part["ra"].astype(float), part["dec"].astype(float),
                        part["z"].astype(float), part["z_type"].astype(str),
                        part["z_err"].astype(float),
                        part["_healpix32"].astype(int), ex))

            if include_pdfs and m.pdf_spec is not None:
                con.execute(
                    "INSERT INTO pdf_specs VALUES (?,?)",
                    (ds_id, json.dumps(raw["pdf_spec"])))
                col = m.pdf_spec.value_column
                con.executemany(
                    "INSERT INTO pdf_payloads VALUES (?,?,?)",
                    ((ds_id, int(g),
                      np.asarray(v, dtype=np.float32).tobytes())
                     for g, v in zip(df["galaxy_id"], df[col])))
        con.commit()
    finally:
        con.close()
    return out


def export_oneuid(con: sqlite3.Connection, members: pd.DataFrame, *,
                  name: str, rules_json: Optional[str] = None,
                  archived_utc: Optional[str] = None) -> int:
    """Insert one ONEUID run (sidecar schema: oneuid, dataset, row_index).

    Bitemporality is relational: the live run has ``archived_utc IS NULL``;
    ``as_of`` queries filter on ``built_utc``/``archived_utc``.
    """
    cur = con.execute(
        "INSERT INTO oneuid_runs (name, rules_json, built_utc, archived_utc)"
        " VALUES (?,?,?,?)",
        (name, rules_json,
         _dt.datetime.now(_dt.timezone.utc).isoformat(), archived_utc))
    run_id = cur.lastrowid
    con.executemany(
        "INSERT INTO oneuid_members VALUES (?,?,?,?)",
        zip([run_id] * len(members), members["oneuid"].astype(int),
            members["dataset"].astype(str), members["row_index"].astype(int)))
    con.commit()
    return run_id


def export_subobject_links(con: sqlite3.Connection, links: pd.DataFrame, *,
                           name: str, relation_type: str) -> None:
    """Insert a sub-object link set (parent→child + optional confidence)."""
    conf = (links["confidence"] if "confidence" in links.columns
            else pd.Series([None] * len(links)))
    payload_cols = [c for c in links.columns
                    if c not in ("parent_oneuid", "child_oneuid", "confidence")]
    payload = (links[payload_cols].apply(
                   lambda r: json.dumps(r.to_dict()), axis=1)
               if payload_cols else pd.Series([None] * len(links)))
    con.executemany(
        "INSERT INTO subobject_links VALUES (?,?,?,?,?,?)",
        zip([name] * len(links), [relation_type] * len(links),
            links["parent_oneuid"].astype(int),
            links["child_oneuid"].astype(int), conf, payload))
    con.commit()


def attach_sql_ddl(sources: Sequence, *, db_name: str = "ouf") -> str:
    """DuckDB zero-copy mode: DDL creating SQL **views over the parquet**.

    No data is moved — the SQL face of wrap-in-place. Run the returned script
    in DuckDB (optional dependency); filter pushdown then prunes partitions
    exactly as ``DatasetView`` does.
    """
    lines = [f"-- oneuniverse attach-mode DDL ({db_name}); run in DuckDB"]
    for src in sources:
        view = _as_view(src)
        glob = str(view.ou_dir / "data" / "**" / "*.parquet")
        tbl = view.manifest.survey_name
        lines.append(
            f"CREATE OR REPLACE VIEW {tbl} AS "
            f"SELECT * FROM read_parquet('{glob}', hive_partitioning=1);")
    return "\n".join(lines)
